[launcher] logging started @ 2025-08-27 17:23:35
DEBUG - asyncio - Using proactor: IocpProactor
Stage Connected
Welcome To Probe Stage
LDC.ldc_manager  INFO     LDC shared memory initialized
LDC.ldc_controller ERROR    [LDC] Connection error: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.
LDC.ldc_manager  ERROR    [LDC Manager] Failed to connect to LDC device
LDC.ldc_manager  ERROR    [LDC Manager] LDC initialization failed
Fail To Connect Tec
DEBUG - pyvisa - No visa library specified, trying to find alternatives.
DEBUG - pyvisa - Environment variable PYVISA_LIBRARY is unset.
DEBUG - pyvisa - No user defined configuration
DEBUG - pyvisa - Automatically found library files: [None, 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa64.dll', 'C:\\WINDOWS\\system32\\visa64.dll']
DEBUG - pyvisa - No user defined library files
DEBUG - pyvisa - The IVI implementation available
DEBUG - pyvisa - No user defined configuration
DEBUG - pyvisa - Automatically found library files: [None, 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa64.dll', 'C:\\WINDOWS\\system32\\visa64.dll']
DEBUG - pyvisa - No user defined library files
DEBUG - pyvisa - Library signatures: 90 ok, 0 failed
DEBUG - pyvisa - Created library wrapper for C:\WINDOWS\system32\visa32.dll
DEBUG - pyvisa - viOpenDefaultRM('<ViObject object at 0x000001BA72FF2A40>',) -> 0
DEBUG - pyvisa - Created ResourceManager with session 1
DEBUG - pyvisa - viParseRsrcEx(1, 'ASRL3::INSTR', 'c_ushort(4)', 'c_ushort(3)', <ctypes.c_char_Array_256 object at 0x000001BA73683BC0>, <ctypes.c_char_Array_256 object at 0x000001BA73683EC0>, <ctypes.c_char_Array_256 object at 0x000001BA73683C40>) -> 0
DEBUG - pyvisa - ASRL3::INSTR - opening ...
DEBUG - pyvisa - viOpen(1, 'ASRL3::INSTR', <AccessModes.no_lock: 0>, 0, '<ViObject object at 0x000001BA72FF2A40>') -> 0
DEBUG - pyvisa - ASRL3::INSTR - is open with session 2
DEBUG - pyvisa - viSetAttribute(2, 1073676321, 115200) -> 0
DEBUG - pyvisa - viSetAttribute(2, 1073676314, 30000) -> 0
DEBUG - pyvisa - viSetAttribute(2, <ResourceAttribute.termchar: 1073676312>, 10) -> 0
DEBUG - pyvisa - viSetAttribute(2, <ResourceAttribute.termchar_enabled: 1073676344>, 0) -> 0
DEBUG - pyvisa - viClear(2,) -> 0
DEBUG - pyvisa - viWrite(2, b'++mode 1\n', 9, 'c_ulong(9)') -> 0
DEBUG - pyvisa - viWrite(2, b'++auto 0\n', 9, 'c_ulong(9)') -> 0
DEBUG - pyvisa - viWrite(2, b'++eos 2\n', 8, 'c_ulong(8)') -> 0
DEBUG - pyvisa - viWrite(2, b'++eoi 1\n', 8, 'c_ulong(8)') -> 0
DEBUG - pyvisa - viWrite(2, b'++ifc\n', 6, 'c_ulong(6)') -> 0
DEBUG - pyvisa - viWrite(2, b'++addr 20\n', 10, 'c_ulong(10)') -> 0
DEBUG - pyvisa - viWrite(2, b'++clr\n', 6, 'c_ulong(6)') -> 0
DEBUG - pyvisa - viWrite(2, b'*IDN?\n', 6, 'c_ulong(6)') -> 0
DEBUG - pyvisa - viWrite(2, b'++read eoi\n', 11, 'c_ulong(11)') -> 0
DEBUG - pyvisa - ASRL3::INSTR - reading 20480 bytes (last status <StatusCode.success_max_count_read: 1073676294>)
DEBUG - pyvisa - viRead(2, <ctypes.c_char_Array_20480 object at 0x000001BA72FF2A40>, 20480, 'c_ulong(0)') -> -1073807339
DEBUG - pyvisa - ASRL3::INSTR - exception while reading: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
Buffer content: bytearray(b'')
ERROR - NIR.nir_manager - [NIR Manager] Connection error: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
Fail To Connect Sensor
